# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "debian-wheezy-chef"
  config.vm.network :forwarded_port, host: 3000, guest: 3000

  config.vm.provision "chef_solo" do |chef|
    chef.json = {
      "mongodb" => {
        "config" => {
          "smallfiles" => "true"
        }
      }
    }
    chef.cookbooks_path = "./cookbooks/"
    chef.add_recipe "strider-cd"
  #   chef.cookbooks_path = "../my-recipes/cookbooks"
  #   chef.roles_path = "../my-recipes/roles"
  #   chef.data_bags_path = "../my-recipes/data_bags"
  #   chef.add_recipe "mysql"
  #   chef.add_role "web"
  #
  #   # You may also specify custom JSON attributes:
  #   chef.json = { :mysql_password => "foo" }
  end
end
